# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/infinix/mt6765-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter x610_h651,$(TARGET_DEVICE)),)

endif
