# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/infinix/mt6765-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/infinix/mt6765-common

PRODUCT_COPY_FILES += \
    vendor/infinix/mt6765-common/proprietary/bin/kpoc_charger:$(TARGET_COPY_OUT_SYSTEM)/bin/kpoc_charger \
    vendor/infinix/mt6765-common/proprietary/bin/netd:$(TARGET_COPY_OUT_SYSTEM)/bin/netd \
    vendor/infinix/mt6765-common/proprietary/etc/init/kpoc_charger.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/kpoc_charger.rc \
    vendor/infinix/mt6765-common/proprietary/lib/libaaudio.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaaudio.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaaudioservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaaudioservice.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudio_param_parser-sys.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudio_param_parser-sys.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudioclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioclient.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudiocomponentengine.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiocomponentengine.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudiocustparam.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiocustparam.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudioflinger.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioflinger.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudiomanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiomanager.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudiopolicycustomextensions.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiopolicycustomextensions.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudiopolicyenginedefault.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiopolicyenginedefault.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudiopolicymanager.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiopolicymanager.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudiopolicymanagerdefault.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiopolicymanagerdefault.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudiopolicyservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiopolicyservice.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudioprocessing.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioprocessing.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudiotoolkit.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiotoolkit.so \
    vendor/infinix/mt6765-common/proprietary/lib/libaudioutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioutils.so \
    vendor/infinix/mt6765-common/proprietary/lib/libbessound_hd_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbessound_hd_mtk.so \
    vendor/infinix/mt6765-common/proprietary/lib/libmtkaudio_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmtkaudio_utils.so \
    vendor/infinix/mt6765-common/proprietary/lib/libshowlogo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshowlogo.so \
    vendor/infinix/mt6765-common/proprietary/lib/libsoundtriggerservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsoundtriggerservice.so \
    vendor/infinix/mt6765-common/proprietary/lib/libsysenv_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsysenv_system.so
