# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/infinix/x610_h651/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/infinix/x610_h651

PRODUCT_COPY_FILES += \
    vendor/infinix/x610_h651/proprietary/lib64/libmtk-ril.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmtk-ril.so
